# Generated by Django 5.2 on 2025-08-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_active_user_admin_user_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
