# Generated by Django 5.2 on 2025-09-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUnreadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_notifications', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='studentnotification',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='studentnotification',
            name='type',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='studentnotification',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
