# Generated by Django 5.2 on 2025-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(default='00000000', max_length=8, unique=True),
        ),
    ]
