class Config {
  static const String backendUrl = 'http://10.0.2.2:8000';
  //'https://cidy.onrender.com'; //
  static const levelsSectionsSubjects = {
    "Première année primaire": {
      "subjects": [
        "Éveil scientifique",
        "Mathématiques",
        "Arabe",
        "Lecture",
        "Dessin",
        "Musique",
        "Éducation physique",
        "Éducation technologique",
        "Éducation islamique",
        "Sport",
      ],
    },
    "Deuxième année primaire": {
      "subjects": [
        "Éveil scientifique",
        "Mathématiques",
        "Arabe",
        "Lecture",
        "Dessin",
        "Musique",
        "Éducation physique",
        "Éducation technologique",
        "Éducation islamique",
        "Sport",
      ],
    },
    "Troisième année primaire": {
      "subjects": [
        "Éveil scientifique",
        "Mathématiques",
        "Arabe",
        "Français",
        "Dessin",
        "Musique",
        "Éducation technologique",
        "Éducation infomatique",
        "Éducation physique",
        "Éducation islamique",
        "Lecture",
        "Sport",
      ],
    },
    "Quatrième année primaire": {
      "subjects": [
        "Éveil scientifique",
        "Mathématiques",
        "Arabe",
        "Français",
        "Dessin",
        "Musique",
        "Éducation technologique",
        "Éducation infomatique",
        "Éducation physique",
        "Éducation islamique",
        "Lecture",
        "Sport",
      ],
    },
    "Cinquième année primaire": {
      "subjects": [
        "Éveil scientifique",
        "Mathématiques",
        "Arabe",
        "Français",
        "Dessin",
        "Musique",
        "Éducation technologique",
        "Éducation infomatique",
        "Éducation physique",
        "Histoire et géographie",
        "Éducation civique",
        "Éducation islamique",
        "Sport",
      ],
    },
    "Sixième année primaire": {
      "subjects": [
        "Anglais",
        "Éducation infomatique",
        "Éducation technologique",
        "Éducation physique",
        "Éducation islamique",
        "Histoire et géographie",
        "Éducation civique",
        "Mathématiques",
        "Éveil scientifique",
        "Français",
        "Arabe",
        "Sport",
      ],
    },
    "Septième année de base": {
      "subjects": [
        "Arabe",
        "Mathématiques",
        "Sciences de la vie et de la Terre",
        "Physique",
        "Histoire et géographie",
        "Éducation islamique",
        "Éducation technologique",
        "Anglais",
        "Français",
      ],
    },
    "Huitième année de base": {
      "subjects": [
        "Arabe",
        "Mathématiques",
        "Sciences de la vie et de la Terre",
        "Physique",
        "Histoire et géographie",
        "Éducation islamique",
        "Éducation technologique",
        "Anglais",
        "Français",
      ],
    },
    "Neuvième année de base": {
      "subjects": [
        "Arabe",
        "Mathématiques",
        "Sciences de la vie et de la Terre",
        "Physique",
        "Histoire et géographie",
        "Éducation islamique",
        "Éducation technologique",
        "Anglais",
        "Français",
      ],
    },
    "Première année secondaire": {
      "sections": {
        "Commun": {
          "subjects": [
            "Arabe",
            "Histoire et géographie",
            "La pensée islamique",
            "Éducation civique",
            "Français",
            "Anglais",
            "Mathématiques",
            "Physique",
            "Sciences de la vie et de la Terre",
            "Technologie",
          ],
        },
        "Sport": {
          "subjects": ["Arabe", "Mathématiques", "Sciences biologiques"],
        },
      },
    },
    "Deuxième année secondaire": {
      "sections": {
        "Lettre": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "La pensée islamique",
            "Éducation civique",
            "Mathématiques",
            "Sciences de la vie et de la Terre",
          ],
        },
        "Science": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Éducation civique",
            "La pensée islamique",
            "Mathématiques",
            "Physique",
            "Sciences de la vie et de la Terre",
            "Technologie",
            "Informatique",
          ],
        },
        "Economie": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Éducation civique",
            "La pensée islamique",
            "Mathématiques",
            "Gestion",
            "Economie",
            "Informatique",
          ],
        },
        "Informatique": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Éducation civique",
            "La pensée islamique",
            "Mathématiques",
            "Physique",
            "Technologie",
            "Informatique",
          ],
        },
        "Sport": {
          "subjects": ["Arabe", "Mathématiques", "Sciences biologiques"],
        },
      },
    },
    "Troisième année secondaire": {
      "sections": {
        "Lettre": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Éducation civique",
            "La pensée islamique",
            "Philosophie",
            "Mathématiques",
            "Informatique",
            "Sciences de la vie et de la Terre",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Economie": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Philosophie",
            "Mathématiques",
            "Gestion",
            "Economie",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Mathématiques": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "La pensée islamique",
            "Philosophie",
            "Mathématiques",
            "Sciences de la vie et de la Terre",
            "Physique",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Science experimentale": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "La pensée islamique",
            "Philosophie",
            "Mathématiques",
            "Sciences de la vie et de la Terre",
            "Physique",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Technique": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Mécanique",
            "Electrique",
            "Informatique",
          ],
        },
        "Informatique": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Algorithmique et Programmation",
            "Technologies de l'information et de la communication",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Sport": {
          "subjects": ["Arabe", "Mathématiques", "Sciences biologiques"],
        },
      },
    },
    "Quatrième année secondaire": {
      "sections": {
        "Lettre": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "La pensée islamique",
            "Philosophie",
            "Mathématiques",
            "Informatique",
            "Sciences de la vie et de la Terre",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Economie": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Philosophie",
            "Mathématiques",
            "Economie",
            "Gestion",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Mathématiques": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Sciences de la vie et de la Terre",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Science experimentale": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Histoire et géographie",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Sciences de la vie et de la Terre",
            "Informatique",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Technique": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Mécanique",
            "Electrique",
            "Informatique",
          ],
        },
        "Informatique": {
          "subjects": [
            "Arabe",
            "Français",
            "Anglais",
            "Philosophie",
            "Mathématiques",
            "Physique",
            "Algorithmique et Programmation",
            "Technologies de l'information et de la communication",
            "Italien",
            "Allemand",
            "Espagnol",
            "Russe",
            "Chinois",
          ],
        },
        "Sport": {
          "subjects": ["Arabe", "Mathématiques", "Sciences biologiques"],
        },
      },
    },
  };
}
