# Generated by Django 5.2 on 2025-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentUnreadNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_notifications', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='parentnotification',
            name='type',
        ),
        migrations.RemoveField(
            model_name='son',
            name='son',
        ),
    ]
