# Generated by Django 5.2 on 2025-09-16 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0002_parentunreadnotification_and_more'),
        ('teacher', '0002_level_remove_class_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='son',
            name='student_teacher_enrollments',
            field=models.ManyToManyField(blank=True, null=True, to='teacher.teacherenrollment'),
        ),
        migrations.AlterField(
            model_name='parentnotification',
            name='meta_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='son',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.level'),
        ),
        migrations.AlterField(
            model_name='son',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.section'),
        ),
        migrations.AddField(
            model_name='parentunreadnotification',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parent.parent'),
        ),
    ]
