# Generated by Django 5.2 on 2025-09-16 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0003_son_student_teacher_enrollments_and_more'),
        ('teacher', '0002_level_remove_class_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='son',
            name='student_teacher_enrollments',
            field=models.ManyToManyField(to='teacher.teacherenrollment'),
        ),
    ]
