# Generated by Django 5.2 on 2025-10-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0004_alter_son_student_teacher_enrollments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='son',
            name='section',
        ),
    ]
