# Generated by Django 5.2 on 2025-09-16 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_level_remove_class_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='join_date',
        ),
        migrations.AddField(
            model_name='teacher',
            name='join_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
