# Generated by Django 5.2 on 2025-09-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_level_name_alter_section_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='absence_date',
        ),
        migrations.RemoveField(
            model_name='class',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='class',
            name='last_status_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
