# Generated by Django 5.2 on 2025-09-30 10:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_remove_class_absence_date_remove_class_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='level',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='section',
        ),
        migrations.AlterField(
            model_name='class',
            name='last_status_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupenrollment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
