# Generated by Django 5.2 on 2025-09-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_remove_section_level_remove_subject_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='last_status_date',
            new_name='last_status_datetime',
        ),
    ]
