# Generated by Django 5.2 on 2025-10-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_rename_last_status_date_class_last_status_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='clear_temporary_schedule_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
