# Generated by Django 5.2 on 2025-10-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parent', '0005_remove_son_section'),
        ('student', '0004_remove_student_section'),
        ('teacher', '0008_alter_group_clear_temporary_schedule_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersubject',
            name='section',
        ),
        migrations.AddField(
            model_name='level',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='levels', to='teacher.subject'),
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
