# Generated by Django 5.2 on 2025-10-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_level_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('attended_and_paid', 'Attended & paid'), ('attended_and_the_payment_not_due', 'Attended & the payment not due'), ('attended_and_the_payment_due', 'Attended & the payment due'), ('absent', 'Absent')], max_length=50),
        ),
    ]
