# Generated by Django 5.2 on 2025-10-23 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_alter_class_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='last_status_datetime',
        ),
        migrations.AddField(
            model_name='class',
            name='absence_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='class',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='status',
            field=models.CharField(choices=[('attended_and_paid', 'Attended & paid'), ('attended_and_the_payment_not_due', 'Attended & the payment not due'), ('attended_and_the_payment_due', 'Attended & the payment due'), ('absent', 'Absent')], max_length=50),
        ),
    ]
