# Generated by Django 5.2 on 2025-11-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_remove_class_last_status_datetime_class_absence_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='section',
            field=models.CharField(default='', max_length=100),
        ),
    ]
