# Generated by Django 5.2 on 2025-09-16 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_section_level_remove_subject_level_and_more'),
        ('parent', '0003_son_student_teacher_enrollments_and_more'),
        ('student', '0003_alter_student_level_alter_student_section_and_more'),
        ('teacher', '0002_level_remove_class_batch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
