from .teacher_serializers import TeacherListSerializer
from .subject_serializers import StudentSubjectListSerializer,StudentSubjectDetailSerializer
from .parent_serializers import ParentListSerializer
from .notification_serializers import StudentNotificationSerializer